// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jznccczfjmatdxdrvszk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6bmNjY3pmam1hdGR4ZHJ2c3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDcxODMsImV4cCI6MjA1MDk4MzE4M30.5XbT0q22t2i2WWCY45_5R249C9NeucorSnpGPXn8LEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);